# Overlays for the Odroid platform

dtbo-$(CONFIG_ARCH_MESON64_ODROIDN2) +=	\
					ads7846.dtbo		\
					can0.dtbo		\
					codec_mm_cma.dtbo	\
					display_vu7c.dtbo	\
					display_vu7c_no_dai.dtbo	\
					fanspeed-full.dtbo		\
					gpio_shortcut.dtbo \
					gpio_spdif.dtbo	\
					hktft32.dtbo		\
					hktft35.dtbo		\
					i2c0.dtbo		\
					i2c1.dtbo		\
					irblaster.dtbo		\
					keymatrix.dtbo		\
					odroidn2-opp.dtbo	\
					odroidn2_plus-opp.dtbo	\
					odroidn2l-opp.dtbo	\
					onewire.dtbo		\
					otg_host_mode.dtbo	\
					pcf8563.dtbo		\
					pwm_backlight.dtbo	\
					pwm_c-pwmfan.dtbo		\
					pwm_cd.dtbo		\
					pwm_ef.dtbo		\
					saradc.dtbo		\
					sdio.dtbo		\
					spi0.dtbo		\
					sx865x-i2c1.dtbo	\
					uart0.dtbo		\
					uart1.dtbo

targets	+= $(dtbo-y)
always	:= $(dtbo-y)
