# Overlays for the Odroid platform

dtbo-$(CONFIG_ARCH_MESON64_ODROIDC4) +=	\
					ads7846.dtbo		\
					can0.dtbo		\
					display_vu7c.dtbo	\
					esp8089.dtbo	\
					fanspeed-full.dtbo	\
					gpio_shortcut.dtbo	\
					hktft32.dtbo		\
					hktft35.dtbo		\
					i2c0.dtbo		\
					i2c1.dtbo		\
					keymatrix.dtbo	\
					onewire.dtbo		\
					otg_host_mode.dtbo	\
					pcf8563.dtbo		\
					pwm_a-pwmfan.dtbo	\
					pwm_ab.dtbo		\
					pwm_backlight.dtbo	\
					pwm_cd.dtbo		\
					pwm_ef.dtbo		\
					sdio.dtbo		\
					spi0.dtbo		\
					sx865x-i2c1.dtbo	\
					uart0.dtbo		\
					uart1.dtbo		\
					uart2.dtbo		\
					uart3.dtbo		\
					wifi_bt_combo.dtbo

targets	+= $(dtbo-y)
always	:= $(dtbo-y)
